### PR TITLE
style rest of pages

### PR DESCRIPTION
**Pull request by LeanKhan**

### CODE REVIEW

**Review by danieliheonu — COMMENTED** [review]
Once election status = "ended" there shouldn't be an add position button
I think the upcoming elections part should only display pending elections

**Comment by danieliheonu** [comment]
The "You have 0 elections" on the dashboard is fixed and not responsive (I don't know if that's the right word)

**Comment by LeanKhan** [comment]
> Once election status = "ended" there shouldn't be an add position button

Okay, thanks.

> I think the upcoming elections part should only display pending elections

 Hmm, okay... But I wanted to show ongoing elections too. But for now we will just leave it to pending. Thanks

**Comment by danieliheonu** [comment]
I think we could have an upcoming election and ongoing election part so people could open the site and still be able to vote if they don't wanna open their email for the link. What do you think?

**Comment by LeanKhan** [comment]
> I think we could have an upcoming election and ongoing election part so people could open the site and still be able to vote if they don't wanna open their email for the link. What do you think?

Okay. Please add it to the backlog, I have pushed updates, including a very basic results page that shows the winner of each category. Of course, we can expand on it to do other cool things. For now, let's get the whole thing ready for the demo tomorrow by God's grace :pray:

**Review by danieliheonu — APPROVED** [review]
Nice work

**Pull request merged**
